In [1]:
import torch

In [2]:
# 没有初始化的矩阵
x = torch.empty(5, 3)
x

tensor([[1.0469e-38, 5.9694e-39, 1.0286e-38],
        [8.9081e-39, 8.9082e-39, 6.9796e-39],
        [9.0919e-39, 9.9184e-39, 6.7960e-39],
        [9.1837e-39, 8.4490e-39, 9.2755e-39],
        [9.6429e-39, 6.1531e-39, 1.1112e-38]])

In [3]:
# 有初始化的矩阵
x = torch.rand(5, 3)
x

tensor([[0.7442, 0.1651, 0.3376],
        [0.5112, 0.4288, 0.3071],
        [0.0628, 0.8153, 0.1578],
        [0.8645, 0.1543, 0.2408],
        [0.7719, 0.7103, 0.4455]])

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x = torch.tensor([2.5, 3.5])
x

tensor([2.5000, 3.5000])

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [10]:
# randn_like：得到相同尺寸的张量
y = torch.randn_like(x, dtype=torch.float)
y

tensor([[-1.1552, -0.0917, -0.8811],
        [-0.7069,  0.9770, -0.0331],
        [ 0.6716,  0.5408,  0.5985],
        [-1.5638,  1.4272, -0.1398],
        [ 0.1239, -0.1088,  0.6812]])

In [9]:
# 本质上返回的是一个tuple
x.size() 

torch.Size([5, 3])

In [15]:
a, b = x.size()
a, b

(5, 3)

#### 加法操作

In [16]:
x + y

tensor([[-0.1552,  0.9083,  0.1189],
        [ 0.2931,  1.9770,  0.9669],
        [ 1.6716,  1.5408,  1.5985],
        [-0.5638,  2.4272,  0.8602],
        [ 1.1239,  0.8912,  1.6812]], dtype=torch.float64)

In [17]:
torch.add(x, y)

tensor([[-0.1552,  0.9083,  0.1189],
        [ 0.2931,  1.9770,  0.9669],
        [ 1.6716,  1.5408,  1.5985],
        [-0.5638,  2.4272,  0.8602],
        [ 1.1239,  0.8912,  1.6812]], dtype=torch.float64)

In [18]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[-0.1552,  0.9083,  0.1189],
        [ 0.2931,  1.9770,  0.9669],
        [ 1.6716,  1.5408,  1.5985],
        [-0.5638,  2.4272,  0.8602],
        [ 1.1239,  0.8912,  1.6812]])

In [19]:
# in-place的操作函数都是带_的后缀
y.add_(x)
y

tensor([[-0.1552,  0.9083,  0.1189],
        [ 0.2931,  1.9770,  0.9669],
        [ 1.6716,  1.5408,  1.5985],
        [-0.5638,  2.4272,  0.8602],
        [ 1.1239,  0.8912,  1.6812]])

#### 切片

In [4]:
x = torch.rand(5, 3)
x

tensor([[0.0011, 0.2451, 0.1776],
        [0.8659, 0.1215, 0.7170],
        [0.0875, 0.4762, 0.2524],
        [0.7556, 0.6473, 0.7856],
        [0.3559, 0.5164, 0.8232]])

In [22]:
x[:, 1]

tensor([0.9854, 0.9872, 0.6876, 0.8815, 0.8381])

In [23]:
# view：保证数据元素的总数量不变
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [24]:
x = torch.randn(1)
x, x.item()

(tensor([-0.5332]), -0.5331604480743408)

In [25]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [26]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [27]:
# Torch Tensor和Numpy array共享底层的内存空间，因此改变其中一个的值，另一个也随之被改变
a.add_(1)
a, b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [28]:
import numpy as np

In [30]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

In [31]:
# 所有在CPU上的Tensors，除了CharTensor，都可以转换为Numpy array并可以反向转换

In [32]:
# Tensors可以用.to()方法来将其移动到任意设备上

In [5]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    # x和y都在GPU上面，才能支持加法运算
    z = x + y
    print(z)

tensor([[1.0011, 1.2451, 1.1776],
        [1.8659, 1.1215, 1.7170],
        [1.0875, 1.4762, 1.2524],
        [1.7556, 1.6473, 1.7856],
        [1.3559, 1.5164, 1.8232]], device='cuda:0')


In [6]:
torch.cuda.is_available()

True