In [1]:
import torch

In [2]:
x1 = torch.ones(3, 3)
x1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [14]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [15]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [16]:
z = x * y * 3
z

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>)

In [17]:
out = z.mean()
out

tensor(9., grad_fn=<MeanBackward0>)

In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
a.requires_grad

False

In [9]:
# 改变Tensor的属性
a.requires_grad_(True)
a.requires_grad

True

In [10]:
b = (a * a).sum()
b

tensor(1633.5282, grad_fn=<SumBackward0>)

In [18]:
# 在PyTorch中，反向传播是依靠.backward()实现的
out.backward()
x.grad

tensor([[3., 3.],
        [3., 3.]])

In [21]:
# 停止自动求导，建议使用
with torch.no_grad():
    print((x ** 2).requires_grad)
    
# 通过.detach()获得一个新的Tensor，拥有相同的内容但不需要自动求导
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
# .eq()纯碎数学值上的比较
print(x.eq(y).all())

False
True
False
tensor(True)
